"""star schema relationships

Revision ID: 767531c6565e
Revises: 0f321c2cf7b5
Create Date: 2026-08-11 15:03:04.996020
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from decisionflow.db.rls import disable_rls, enable_rls

revision: str = "767531c6565e"
down_revision: str | None = "0f321c2cf7b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Pinned to the tables this revision creates. See the ingestion-core migration
# for why this is never imported from application code.
RLS_TABLES = ("dataset_relationships",)

# `op.add_column` does not emit CREATE TYPE for an enum — only `create_table`
# does — so adding an enum column to an existing table fails with
# 'type "table_role" does not exist' unless the type is created first.
# `create_type=False` then stops SQLAlchemy trying to create it a second time.
table_role = postgresql.ENUM(
    "fact", "dimension", "unknown", name="table_role", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_relationships",
        sa.Column("from_dataset_id", sa.UUID(), nullable=False),
        sa.Column("from_column", sa.String(length=300), nullable=False),
        sa.Column("to_dataset_id", sa.UUID(), nullable=False),
        sa.Column("to_column", sa.String(length=300), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("rationale", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_relationships_from_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_dataset_relationships_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_relationships_to_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_relationships")),
        sa.UniqueConstraint(
            "from_dataset_id",
            "from_column",
            "to_dataset_id",
            "to_column",
            name="uq_dataset_relationships_edge",
        ),
    )
    op.create_index(
        op.f("ix_dataset_relationships_from_dataset_id"),
        "dataset_relationships",
        ["from_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_relationships_org_id"), "dataset_relationships", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_relationships_to_dataset_id"),
        "dataset_relationships",
        ["to_dataset_id"],
        unique=False,
    )
    table_role.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "datasets",
        sa.Column(
            "table_role",
            table_role,
            server_default=sa.text("'unknown'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        for statement in enable_rls(table):
            op.execute(statement)


def downgrade() -> None:
    for table in RLS_TABLES:
        for statement in disable_rls(table):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "table_role")
    op.drop_index(
        op.f("ix_dataset_relationships_to_dataset_id"), table_name="dataset_relationships"
    )
    op.drop_index(op.f("ix_dataset_relationships_org_id"), table_name="dataset_relationships")
    op.drop_index(
        op.f("ix_dataset_relationships_from_dataset_id"), table_name="dataset_relationships"
    )
    op.drop_table("dataset_relationships")
    # ### end Alembic commands ###

    # Dropping the column leaves the type behind, which then blocks a re-run.
    table_role.drop(op.get_bind(), checkfirst=True)
