"""semantic layer and kpis

Revision ID: ab244fcf22ad
Revises: 83eec7b6e57a
Create Date: 2026-08-09 11:37:26.118047
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from decisionflow.db.rls import disable_rls, enable_rls

revision: str = "ab244fcf22ad"
down_revision: str | None = "83eec7b6e57a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Pinned to the tables this revision creates. See the ingestion-core migration
# for why this is never imported from application code.
RLS_TABLES = ("kpis",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpis",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value", sa.Numeric(precision=38, scale=6), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("higher_is_better", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_kpis_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_kpis_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpis")),
        sa.UniqueConstraint("dataset_id", "key", name="uq_kpis_dataset_id_key"),
    )
    op.create_index(op.f("ix_kpis_dataset_id"), "kpis", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_kpis_org_id"), "kpis", ["org_id"], unique=False)
    op.add_column(
        "dataset_columns", sa.Column("semantic_role", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "dataset_columns",
        sa.Column(
            "semantic_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("dataset_columns", sa.Column("semantic_rationale", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        for statement in enable_rls(table):
            op.execute(statement)


def downgrade() -> None:
    for table in RLS_TABLES:
        for statement in disable_rls(table):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset_columns", "semantic_rationale")
    op.drop_column("dataset_columns", "semantic_tags")
    op.drop_column("dataset_columns", "semantic_role")
    op.drop_index(op.f("ix_kpis_org_id"), table_name="kpis")
    op.drop_index(op.f("ix_kpis_dataset_id"), table_name="kpis")
    op.drop_table("kpis")
    # ### end Alembic commands ###
