"""ingestion core

Revision ID: 86e87d553934
Revises: 2de5120c5d1a
Create Date: 2026-08-08 12:39:46.974044
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from decisionflow.db.rls import disable_rls, enable_rls

revision: str = "86e87d553934"
down_revision: str | None = "2de5120c5d1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Pinned to the tables *this* revision creates, never imported from application
# code. A migration is a snapshot of one moment: if this read a live constant,
# adding a tenant table in a later module would retroactively change what this
# revision tries to do, and a from-scratch upgrade would fail on tables that do
# not exist yet.
#
# The guarantee that every tenant table actually gets a policy is enforced in
# tests/test_rls.py, which derives the list from the live schema instead.
RLS_TABLES = ("data_sources", "datasets", "dataset_columns", "ingestion_runs")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "file_upload", "postgres", "mysql", "sqlserver", "rest_api", name="source_kind"
            ),
            nullable=False,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("org_id", "name", name="uq_data_sources_org_id_name"),
    )
    op.create_index(op.f("ix_data_sources_org_id"), "data_sources", ["org_id"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("uploaded", "analyzing", "ready", "failed", name="dataset_status"),
            server_default=sa.text("'uploaded'"),
            nullable=False,
        ),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.String(length=400), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=600), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_datasets_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_datasets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_datasets_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("org_id", "slug", name="uq_datasets_org_id_slug"),
    )
    op.create_index(op.f("ix_datasets_org_id"), "datasets", ["org_id"], unique=False)
    op.create_index("ix_datasets_org_id_status", "datasets", ["org_id", "status"], unique=False)
    op.create_index(op.f("ix_datasets_source_id"), "datasets", ["source_id"], unique=False)
    op.create_table(
        "dataset_columns",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column(
            "data_type",
            sa.Enum(
                "string",
                "integer",
                "decimal",
                "boolean",
                "date",
                "timestamp",
                "unknown",
                name="column_type",
            ),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=120), nullable=True),
        sa.Column("nullable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "sample_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_columns_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_dataset_columns_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_columns")),
        sa.UniqueConstraint(
            "dataset_id", "position", name="uq_dataset_columns_dataset_id_position"
        ),
    )
    op.create_index(
        op.f("ix_dataset_columns_dataset_id"), "dataset_columns", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_dataset_columns_org_id"), "dataset_columns", ["org_id"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "failed", name="run_status"),
            server_default=sa.text("'running'"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_ingested", sa.BigInteger(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_ingestion_runs_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_ingestion_runs_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_dataset_id"), "ingestion_runs", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_org_id"), "ingestion_runs", ["org_id"], unique=False)
    # ### end Alembic commands ###

    # Autogenerate cannot see RLS policies, so tenant isolation is applied by
    # hand. These are the first tables holding customer data, and therefore the
    # first where a missing filter would be a cross-tenant leak rather than a
    # bug. Driven off ORG_SCOPED_TABLES so a new tenant table cannot be added
    # without also being protected — the RLS test asserts the two agree.
    for table in RLS_TABLES:
        for statement in enable_rls(table):
            op.execute(statement)


def downgrade() -> None:
    for table in RLS_TABLES:
        for statement in disable_rls(table):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_runs_org_id"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_dataset_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_dataset_columns_org_id"), table_name="dataset_columns")
    op.drop_index(op.f("ix_dataset_columns_dataset_id"), table_name="dataset_columns")
    op.drop_table("dataset_columns")
    op.drop_index(op.f("ix_datasets_source_id"), table_name="datasets")
    op.drop_index("ix_datasets_org_id_status", table_name="datasets")
    op.drop_index(op.f("ix_datasets_org_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_data_sources_org_id"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
