"""profiling and cleaning

Revision ID: 83eec7b6e57a
Revises: 86e87d553934
Create Date: 2026-08-08 13:03:56.957540
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from decisionflow.db.rls import disable_rls, enable_rls

revision: str = "83eec7b6e57a"
down_revision: str | None = "86e87d553934"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Pinned to the tables this revision creates. See the ingestion-core migration
# for why this is never imported from application code.
RLS_TABLES = ("data_quality_issues",)


def _apply_rls() -> None:
    for table in RLS_TABLES:
        for statement in enable_rls(table):
            op.execute(statement)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_issues",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column(
            "code",
            sa.Enum(
                "empty_column",
                "high_null_rate",
                "constant_column",
                "duplicate_rows",
                "mixed_types",
                "outliers",
                "high_cardinality",
                "empty_dataset",
                name="issue_code",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity", sa.Enum("info", "warning", "error", name="issue_severity"), nullable=False
        ),
        sa.Column("column_name", sa.String(length=300), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_data_quality_issues_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_data_quality_issues_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_issues")),
    )
    op.create_index(
        op.f("ix_data_quality_issues_dataset_id"),
        "data_quality_issues",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_quality_issues_dataset_id_severity",
        "data_quality_issues",
        ["dataset_id", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_issues_org_id"), "data_quality_issues", ["org_id"], unique=False
    )
    op.add_column(
        "dataset_columns",
        sa.Column(
            "profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "dataset_columns",
        sa.Column(
            "cleaned_type",
            sa.Enum(
                "string",
                "integer",
                "decimal",
                "boolean",
                "date",
                "timestamp",
                "unknown",
                name="column_type",
            ),
            nullable=True,
        ),
    )
    op.add_column("datasets", sa.Column("clean_row_count", sa.BigInteger(), nullable=True))
    op.add_column("datasets", sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("datasets", sa.Column("quality_score", sa.Integer(), nullable=True))
    op.add_column(
        "datasets",
        sa.Column(
            "cleaning_actions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    _apply_rls()


def downgrade() -> None:
    for table in RLS_TABLES:
        for statement in disable_rls(table):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "cleaning_actions")
    op.drop_column("datasets", "quality_score")
    op.drop_column("datasets", "cleaned_at")
    op.drop_column("datasets", "clean_row_count")
    op.drop_column("dataset_columns", "cleaned_type")
    op.drop_column("dataset_columns", "profile")
    op.drop_index(op.f("ix_data_quality_issues_org_id"), table_name="data_quality_issues")
    op.drop_index("ix_data_quality_issues_dataset_id_severity", table_name="data_quality_issues")
    op.drop_index(op.f("ix_data_quality_issues_dataset_id"), table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    # ### end Alembic commands ###
